### ISSUE TITLE
Update link to 'Am I Ready?' page

### ISSUE THREAD

**Issue by maxatdetroit** [CityOfDetroit/dpa-eligibility-survey#6]
https://training.detroitmi.gov/departments/housing-and-revitalization-department/detroit-down-payment-assistance-program/am-i-ready

Should become

/departments/housing-and-revitalization-department/detroit-down-payment-assistance-program/am-i-ready

so that the user is redirected to the right page in any environment (training, dev, prod, etc.)

**Comment by dvelle** [comment]
looks good
